### PR TITLE
Update logger dependencies

### PR DESCRIPTION
**Pull request by mans0954**
This reduces the number of sha1 hashes in `packag-lock.json` from 145 to 134.

See https://github.com/overleaf/issues/issues/3252 and https://github.com/overleaf/analytics/pull/363

### CODE REVIEW

**Comment by briangough** [comment]
I can publish this again - let me know if you are ready for me to do that.

**Comment by mans0954** [comment]
> I can publish this again - let me know if you are ready for me to do that.

I don't know where the 134 are coming from. Is it worth me updating @overleaf/o-error as well to see if that pulls it down further?

**Comment by mans0954** [comment]
> I don't know where the 134 are coming from. Is it worth me updating @overleaf/o-error as well to see if that pulls it down further?

o-error has no non-dev dependencies. Presumably o-error dev dependencies aren't pulled into modules using it?

**Comment by briangough** [comment]
Yes, I think it's worth updating everything. `npm upgrade` and `npm audit fix`.

**Comment by briangough** [comment]
Take a look at `npm outdated`

```
$ npm outdated
Package                       Current  Wanted  Latest  Location
@google-cloud/logging-bunyan    2.0.3   2.0.3   3.0.0  logger-sharelatex
bunyan                         1.8.12  1.8.12  1.8.14  logger-sharelatex
eslint                          6.8.0   6.8.0   7.3.1  logger-sharelatex
eslint-config-prettier          3.6.0   3.6.0  6.11.0  logger-sharelatex
eslint-config-standard         11.0.0  11.0.0  14.1.1  logger-sharelatex
eslint-plugin-chai-expect       1.2.0   1.2.0   2.1.0  logger-sharelatex
eslint-plugin-chai-friendly     0.4.1   0.4.1   0.6.0  logger-sharelatex
eslint-plugin-mocha             5.3.0   5.3.0   7.0.1  logger-sharelatex
eslint-plugin-node              6.0.1   6.0.1  11.1.0  logger-sharelatex
eslint-plugin-promise           3.8.0   3.8.0   4.2.1  logger-sharelatex
eslint-plugin-standard          3.1.0   3.1.0   4.0.1  logger-sharelatex
mocha                           5.2.0   5.2.0   8.0.1  logger-sharelatex
prettier                       1.19.1  1.19.1   2.0.5  logger-sharelatex
raven                           1.1.3   1.1.3   2.6.4  logger-sharelatex
sandboxed-module                2.0.3   2.0.3   2.0.4  logger-sharelatex
sinon                           7.2.3   7.2.3   9.0.2  logger-sharelatex
sinon-chai                      3.3.0   3.3.0   3.5.0  logger-sharelatex
yn                              3.1.1   3.1.1   4.0.0  logger-sharelatex
```

**Comment by mans0954** [comment]
I get
```
npm outdated
Package  Current  Wanted  Latest  Location
eslint     6.8.0   6.8.0   7.3.1  logger-sharelatex
```
I didn't update eslint beyond 6.8.0 due to this issue: https://github.com/prettier/prettier-eslint-cli/issues/208

**Comment by mans0954** [comment]
In any case, upgrading eslint to 7.3.1 still leaves 134 sha1s.

**Comment by briangough** [comment]
> I get
> 
> ```
> npm outdated
> Package  Current  Wanted  Latest  Location
> eslint     6.8.0   6.8.0   7.3.1  logger-sharelatex
> ```
> 
> I didn't update eslint beyond 6.8.0 due to this issue: [prettier/prettier-eslint-cli#208](https://github.com/prettier/prettier-eslint-cli/issues/208)

Ok, that's good. I had run it `npm outdated` on master so it wasn't including the updates already on this branch.

**Comment by mans0954** [comment]
@briangough I don't think there's any more I can do at this stage, so do you want to publish?

**Comment by das7pad** [comment]
> I get
> 
> ```
> npm outdated
> Package  Current  Wanted  Latest  Location
> eslint     6.8.0   6.8.0   7.3.1  logger-sharelatex
> ```
> 
> I didn't update eslint beyond 6.8.0 due to this issue: [prettier/prettier-eslint-cli#208](https://github.com/prettier/prettier-eslint-cli/issues/208)

This is easy to fix: https://github.com/overleaf/logger-module/pull/21

**Comment by briangough** [comment]
A new version of the package logger-sharelatex (2.1.1) was published at 2020-07-02T13:01:40.037Z from
X.X.X.X. The shasum of this package was 0df62c3a669c43a17bf3ac8cbfd8d7cd29c9ffd0.

**Pull request merged**
